version: 2
updates:
  # Maintain dependencies for NuGet packages
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
